### ISSUE TITLE
Assets URL, when site is with script name "index.php"

### ISSUE THREAD

**Issue by Ainaras** [jackboberg/CodeIgniter-Assets#5] opened 2013-02-23 13:01 UTC
Hi,
I use CI environment, where in config is:

``` php
$config['index_page'] = 'index.php';
```

Then i add static asset (CSS) with 

``` php
$this->assets->add('example.css')
```

In view is output get_styles(). Here i need URL to my asset "http://example.com/example.css" or "/example.css", but i get "http://example.com/index.php/example.css". I know, that here is specific case, but i think, that library must always right be.

**Comment by jackboberg** [comment] 2013-02-23 17:15
duplicate of issue #3 fixed, thanks

**Closed as completed by jackboberg** 2013-02-23 17:15 UTC
